package crewaiadapter

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lutherfourie/vibe/go/internal/crewai"
	"github.com/lutherfourie/vibe/go/internal/lanes"
)

func TestHumanGateBlocksLiveWithoutForce(t *testing.T) {
	fr := &crewai.FakeRunner{Stdout: "should-not-run"}
	b := NewBackend(fr)

	req := crewai.ExecuteRequest{
		Lane:    lanes.Lane{Name: "livegate"},
		CrewDir: t.TempDir(),
		DryRun:  false,
		ForceRun: false,
	}
	res, err := b.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("unexpected err: %v", err)
	}
	if !res.Gated {
		t.Fatalf("expected Gated=true")
	}
	if res.Success {
		t.Fatalf("expected Success=false for gated")
	}
	if !strings.Contains(res.Output, "VIBE_GATE: human approval required (human.before_runtime)") {
		t.Fatalf("gate output missing marker: %s", res.Output)
	}
	if fr.CallCount() != 0 {
		t.Fatalf("runner must not be called on gated path, calls=%d", fr.CallCount())
	}
}

func TestDryRunCallsRunnerAppendsCheckpoint(t *testing.T) {
	root := t.TempDir()
	crewDir := filepath.Join(root, "crew")
	if err := os.MkdirAll(crewDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(crewDir, "crew.py"), []byte("# generated by P1\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	fr := &crewai.FakeRunner{
		Stdout: "DRY crewai run for lane: drylane\nVIBE_CHECKPOINT: drylane completed\ncheckpoint written\n",
	}
	b := NewBackend(fr)

	prog := filepath.Join(root, "PROGRESS.md")
	req := crewai.ExecuteRequest{
		Lane:         lanes.Lane{Name: "drylane", Writes: []string{"."}},
		CrewDir:      crewDir,
		RootDir:      root,
		ProgressPath: "PROGRESS.md",
		DryRun:       true,
	}
	res, err := b.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("dry exec err: %v", err)
	}
	if !res.Success {
		t.Fatalf("expected Success=true, got false. out=%s", res.Output)
	}
	if fr.CallCount() != 1 {
		t.Fatalf("expected runner called once, got %d", fr.CallCount())
	}
	if !strings.Contains(res.Output, "drylane") {
		t.Fatalf("output must contain lane name: %s", res.Output)
	}
	if !strings.Contains(res.Output, "checkpoint written") {
		t.Fatalf("output must indicate checkpoint written: %s", res.Output)
	}
	if !res.Checkpointed {
		t.Fatalf("expected Checkpointed=true")
	}

	// Verify real progress was appended
	data, err := os.ReadFile(prog)
	if err != nil {
		t.Fatalf("PROGRESS.md not written: %v", err)
	}
	if !strings.Contains(string(data), "crewai executor drylane") {
		t.Fatalf("progress missing checkpoint entry:\n%s", string(data))
	}
}

func TestWriteScopeGuardRejectsOutOfScope(t *testing.T) {
	root := t.TempDir()
	// inside-root crew dir that is NOT covered by the writes
	badCrew := filepath.Join(root, "evil", "out")
	if err := os.MkdirAll(badCrew, 0o755); err != nil {
		t.Fatal(err)
	}
	// Note: do NOT create crew.py — guard runs before validate
	fr := &crewai.FakeRunner{}
	b := NewBackend(fr)

	req := crewai.ExecuteRequest{
		Lane:    lanes.Lane{Name: "scoped", Writes: []string{"docs"}},
		CrewDir: badCrew,
		RootDir: root,
		DryRun:  true,
	}
	_, err := b.Execute(context.Background(), req)
	if err == nil {
		t.Fatalf("expected loud write-scope guard error")
	}
	if !strings.Contains(err.Error(), "write-scope guard") {
		t.Fatalf("error must mention write-scope guard: %v", err)
	}
	if fr.CallCount() != 0 {
		t.Fatalf("runner must not be invoked on guard failure")
	}
}

func TestForceRunBypassesGateButStillDryAndCheckpoints(t *testing.T) {
	root := t.TempDir()
	crewDir := filepath.Join(root, "crew-force")
	if err := os.MkdirAll(crewDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(crewDir, "crew.py"), []byte("# dummy\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	fr := &crewai.FakeRunner{
		Stdout: "DRY (force) for lane: forcelane\nVIBE_CHECKPOINT: forcelane completed\ncheckpoint written\n",
	}
	b := NewBackend(fr)

	prog := filepath.Join(root, "FORCE_PROGRESS.md")
	req := crewai.ExecuteRequest{
		Lane:         lanes.Lane{Name: "forcelane", Writes: []string{"."}},
		CrewDir:      crewDir,
		RootDir:      root,
		ProgressPath: "FORCE_PROGRESS.md",
		DryRun:       false,
		ForceRun:     true,
	}
	res, err := b.Execute(context.Background(), req)
	if err != nil {
		t.Fatalf("force exec err: %v", err)
	}
	if !res.Success {
		t.Fatalf("expected success under ForceRun")
	}
	if res.Gated {
		t.Fatalf("must not be gated under ForceRun")
	}
	if fr.CallCount() != 1 {
		t.Fatalf("runner should run under ForceRun, got %d", fr.CallCount())
	}
	if !strings.Contains(res.Output, "forcelane") || !strings.Contains(res.Output, "checkpoint written") {
		t.Fatalf("output missing lane/checkpoint indication: %s", res.Output)
	}
	if !res.Checkpointed {
		t.Fatalf("ForceRun path must still parse marker and append checkpoint")
	}
	data, _ := os.ReadFile(prog)
	if !strings.Contains(string(data), "forcelane") {
		t.Fatalf("force progress missing entry")
	}
}
