package crewaiadapter

import (
	"fmt"
	"os"
	"path/filepath"
)

// ValidateCrewDir fails loud if the dir does not contain crew.py.
// This is called by executor when a run is requested (after human gate decision).
func ValidateCrewDir(crewDir string) error {
	if crewDir == "" {
		return fmt.Errorf("crew dir is empty")
	}
	crewPy := filepath.Join(crewDir, "crew.py")
	if _, err := os.Stat(crewPy); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("crew.py missing in %s (required for run)", crewDir)
		}
		return fmt.Errorf("crew.py check failed: %w", err)
	}
	return nil
}

// LocateOrValidate looks for a crew dir containing crew.py. It prefers an explicit
// suggested path, then falls back to a conventional location under base. Thin only —
// does not generate code (compiler is in packages/language).
func LocateOrValidate(base, suggested string) (string, error) {
	if suggested != "" {
		if err := ValidateCrewDir(suggested); err == nil {
			return suggested, nil
		}
	}
	if base != "" {
		cand := filepath.Join(base, ".vibe-out", "crew")
		if err := ValidateCrewDir(cand); err == nil {
			return cand, nil
		}
		// also try flat
		cand2 := filepath.Join(base, "crew")
		if err := ValidateCrewDir(cand2); err == nil {
			return cand2, nil
		}
	}
	return "", fmt.Errorf("could not locate valid crew dir (crew.py) under base=%s suggested=%s", base, suggested)
}

// WriteShim writes a tiny non-functional vibe_run.py shim into the crew dir.
// It is a hook surface for future real invocation; harmless for dry/mock.
func WriteShim(crewDir, laneName string) error {
	if crewDir == "" {
		return fmt.Errorf("no crew dir for shim")
	}
	shim := fmt.Sprintf(`#!/usr/bin/env python3
# vibe_run shim (thin, generated by adapters/crewai) for lane %s
# Real crew execution is performed via flow/crew kickoff under Vibe supervision.
# This shim is for contract surface only.
print("VIBE_SHIM_START lane=%s")
`, laneName, laneName)
	return os.WriteFile(filepath.Join(crewDir, "vibe_run.py"), []byte(shim), 0o755)
}
